### ISSUE TITLE
Error to parse curly braces within a string

### ISSUE THREAD

**Issue by bbigras** [gvolpe/dconf2nix#10]
When I ran dconf2nix my computer soft-froze.

My dconf.settings is 12k.

**Comment by gvolpe** [comment]
Can you share your `dconf` dump?

**Comment by bbigras** [comment]
try this:

```
[org/virt-manager/virt-manager/urls]
isos=['/home/bbigras/Downloads/something {ddsa}']
```

**Comment by gvolpe** [comment]
Cool, I edited the issue title to describe the issue. You can usually run `dconf2nix` with the `--verbose` flag to see what's going on and in case it cannot parse something it would hang (that's something I should probably fix too). The high CPU and memory usage is likely due to the program hanging.

**Comment by gvolpe** [comment]
@bbigras if you can, I'd kindly ask you to remove these values and run it again to see if there are more issues. I will fix it as soon as I can. I'm on CET timezone so now's a bit late but it's great to see someone out there is giving `dconf2nix` a try and reporting issues :)

**Comment by bbigras** [comment]
> @bbigras if you can, I'd kindly ask you to remove these values and run it again to see if there are more issues. I will fix them as soon as I can to avoid making more releases. I'm on CET timezone so now's a bit late but it's great to see someone out there is giving `dconf2nix` a try and reporting issues :)

Yeah it ran fine without the curly braces. :)

**Comment by gvolpe** [comment]
Great, I'll make another release then, thanks for reporting back :)

**Comment by gvolpe** [comment]
Be aware of the caveats mentioned in the README file, though. Home Manager doesn't support the full protocol so even if the dconf file is converted into nix, there's a chance not all the stuff will actually work.

**Comment by gvolpe** [comment]
Released a new version with the fix: https://github.com/gvolpe/dconf2nix/releases/tag/v0.0.4
