### ISSUE TITLE
Support dumping custom paths instead of just `/`

### ISSUE THREAD

**Issue by austinbutler** [gvolpe/dconf2nix#22]
**Dumped Tilix config**

```sh
❯ dconf dump /com/gexperts/Tilix/
```

```ini
[profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d]
font='MesloLGS Nerd Font 11'
use-system-font=false
visible-name='Default'
```

**Converted Tilix config**

```sh
❯ dconf2nix -i tilix.conf -o tilix.nix
```

```nix
# Generated via dconf2nix: https://github.com/gvolpe/dconf2nix
{ lib, ... }:

let
  mkTuple = lib.hm.gvariant.mkTuple;
in
{
  dconf.settings = {
    "profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d" = {
      "font" = "MesloLGS Nerd Font 10";
      "use-system-font" = false;
      "visible-name" = "Default";
    };

  };
}
```

**Resulting incorrect dconf config**

```sh
❯ dconf dump /profiles/
```

```ini
[2b7c4080-0ddd-46c5-8f23-563fd3ba789d]
font='MesloLGS Nerd Font 11'
use-system-font=false
visible-name='Default'
```

**The config that actually works**

```nix
{
  home-manager.users.austin = { pkgs, ... }: {
    dconf.settings = {
      "com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d" = {
        font = "MesloLGS Nerd Font 11";
        use-system-font = false;
        visible-name = "Default";
      };
    };
  };
}
```

**Comment by austinbutler** [comment]
Actually I see what's happening, and it's a me problem :face_with_head_bandage:. `dconf2nix` can't know where to place the dump when it's not at the root level. Not sure what I was expecting...

I suppose the only suggestion I could offer is a warning or something in the README about dumping keys other than root.

**Comment by gvolpe** [comment]
I think we could add support for dumping keys other than `/`, maybe something like: 

```shell
$ dconf dump /com/gexperts/Tilix/ | dconf2nix --root /com/gexperts/Tilix/ > dconf.nix
```

Though, I'm not sure how common this use case may be.

**Comment by gvolpe** [comment]
@austinbutler have a look at #23 and let me know if that looks good to you or you have other suggestions :)

**Comment by austinbutler** [comment]
@gvolpe that looks great, thanks! At the very least it at least makes it more clear that it's expecting the root by default, which should help dummies like myself in the future :wink:.
