### ISSUE TITLE
Negative term in mkTuple

### ISSUE THREAD

**Issue by michzappa** [gvolpe/dconf2nix#31]
Using dfconf2nix as found in https://gvolpe.com/blog/gnome3-on-nixos/ (excellent guide thank you), it gave a .nix file which contains a syntax error in mkTuple. 

If either of the two numbers is negative, it is an "unexpected '-'" to the syntax checker of Nix. This came up in the "org/gnome/settings-daemon/plugins/color/night-light-last-coordinates" section of the dconf.settings. 

I made it a string ("-71.xxxx" instead of -71.xxxx) and there is no longer a syntax error but I don't know if it is still performing correctly.

Have you seen this before?

Thank you

**Comment by michzappa** [comment]
This appears to only be an issue with the version from nix-env. I added it as a system package and it is no longer occurring. Thank you for this program.

**Comment by johanbrandhorst** [comment]
I'm still seeing this in version 0.0.7

**Comment by johanbrandhorst** [comment]
Nevermind, I was running an old version, sorry!

**Comment by johanbrandhorst** [comment]
This is still present in v0.0.8. The following input:

```
[org/gnome/settings-daemon/plugins/color]
night-light-last-coordinates=(43.684199280057591, -79.347200000000001)
```

Produces
```
# Generated via dconf2nix: https://github.com/gvolpe/dconf2nix
{ lib, ... }:

let
  mkTuple = lib.hm.gvariant.mkTuple;
in
{
  dconf.settings = {
    "org/gnome/settings-daemon/plugins/color" = {
      night-light-last-coordinates = mkTuple [ 43.68419928005759 -79.3472 ];
    };
}
```
