### ISSUE TITLE
Timeout when dconf.settings has ('xkb', 'us+alt-intl') [org/gnome/desktop/input-sources]

### ISSUE THREAD

**Issue by michzappa** [gvolpe/dconf2nix#32]
[org/gnome/desktop/input-sources]
current='uint32 0'
sources=[('xkb', 'us+alt-intl')]
xkb-options=['terminate:ctrl_alt_bksp', 'lv3:ralt_switch']

The above addition to my dconf.settings file makes dconf2nix time out when trying to parse into a .nix file. It also times out when there is a list of multiple sources and 'us+alt-intl' is one of them, but not when it is a list of sources like 'us' and 'fr'. Curious if it is because of the '+' and '-' in the keyboard name. 

Edit 1: But looking at Dconf.hs on line 66 it seems to allow for these characters in Strings.
Edit 2: It seems the commit that allows '+' in Strings came after the last release. I will try using the master branch.

**Comment by michzappa** [comment]
This was fixed by building the master branch. I look forward to the next release!

**Comment by gvolpe** [comment]
This has been fixed in #29 but I forgot to make a new release. If you try out `master` instead, this should work.

**Comment by gvolpe** [comment]
@michzappa I just published a new release: https://github.com/gvolpe/dconf2nix/releases/tag/v0.0.7

It'll take a while until the new version reaches `nixpkgs` unstable, though, so it's always better to use an overlay to be on the latest version.
