### ISSUE TITLE
dconf2nix should invert special case for empty string lists

### ISSUE THREAD

**Issue by johanbrandhorst** [gvolpe/dconf2nix#34]
The fix for https://github.com/nix-community/home-manager/issues/769 introduced a special case for empty string lists when parsing the config. In short the following mapping happens:

```
[] -> @as []
```

See the logic here: https://github.com/nix-community/home-manager/commit/5d054abe6aa790da041d5ebd14fe44cc888d86bf#diff-1afc90afe9ca8ef2ec31b8fcee765e03d38679506e051053848e4b14aed57bbaR22.

`dconf2nix` should invert this logic, so the following mapping happens:

```
@as [] -> []
```

Currently, this configuration value maps to

```
"@as []"
```

This mapping breaks keybindings which unset keys.

**Comment by johanbrandhorst** [comment]
Thanks for the quick turnaround 😄

**Comment by gvolpe** [comment]
No problems, you caught me at home with some time to kill :) 

I cut a new release: https://github.com/gvolpe/dconf2nix/releases/tag/v0.0.8, should hit `nixpkgs` in a couple of days.
