### ISSUE TITLE
Using `mk` functions

### ISSUE THREAD

**Issue by rycee** [gvolpe/dconf2nix#43]
I noticed in https://github.com/nix-community/home-manager/issues/2249 that dconf2nix generates output in a "raw" dconf format, for example, the uint32 value 0 is emitted as a Nix string `"uint32 0"`. This is not really the intended way to construct GVariant values in the HM library. The recommended way to emit values is to use the various `mk` functions as [described in the manual](https://nix-community.github.io/home-manager/index.html#sec-option-types) (scroll down to where `hm.types.gvariant` starts).

For example, instead of having `"uint32 0"` one would use `lib.hm.gvariant.mkUint32 0`. Using the functions should be considerably more robust.

Btw, very neat project! Good job 🙂

**Comment by rycee** [comment]
Btw, you can see the functions in action in the [gvariant test case](https://github.com/nix-community/home-manager/blob/a3d691c05308b43afe264a2165f60948cfd2963e/tests/lib/types/gvariant-merge.nix).

**Comment by gvolpe** [comment]
Thanks a lot @rycee ! Didn't know about those `mk` functions, will get it don soon :)

**Comment by parthy** [comment]
Thanks to both of you for taking care of this! It works perfectly now.
