### ISSUE TITLE
Emoji causes `timeout`

### ISSUE THREAD

**Issue by seandlg** [gvolpe/dconf2nix#69]
### Type of bug

Timeout

### Version

0.0.11

### Did you test against master?

- [x] Certainly

### DConf input

```ini
[org/gnome/Characters]
recent-characters=['💡']
```

### Additional context

`dcon2nix --verbose` shows how the Emoji is converted:
```txt
dconf: "[org/gnome/Characters]\nrecent-characters=['\128161']\n"
```

**Comment by gvolpe** [comment]
@seandlg thanks for the report. Can you confirm the fix works using the latest `master`? I can make a release then.

**Comment by seandlg** [comment]
Thanks Gabriel, I am happy to confirm that the fix works :pray:
