### ISSUE TITLE
Set up CI build

### ISSUE THREAD

**Issue by gvolpe** [gvolpe/dconf2nix#7]

**Comment by bbigras** [comment]
Check https://github.com/nix-dot-dev/getting-started-nix-template. It's awesome.

I use almost the same thing for https://github.com/bbigras/nix-matrix-yggdrasil

**Comment by gvolpe** [comment]
Not sure that's the same, I meant a Haskell CI build where the project can compile and run (some missing) tests.

**Comment by bbigras** [comment]
Some tests that you don't want to include in this repo?

Otherwise, github actions with cachix is fast and awesome.

**Comment by gvolpe** [comment]
Some tests I haven't yet written! :joy: 

But yeah, Github actions and Cachix are my go-to option normally :)
