### ISSUE TITLE
Error unexpected "%"

### ISSUE THREAD

**Issue by BenediktBroich** [gvolpe/dconf2nix#73]
### Type of bug

Parsing error

### Version

0.0.11

### Did you test against master?

- [ ] Certainly

### Error message (if not timeout)

```shell
dconf2nix: "<stdin>" (line 885, column 18):
unexpected "%"
expecting "'", letter or digit, space, "=", "$", "!", "&", "+", "-", "_", "(", ")", "[", "]", "{", "}", ",", "#", "@", "\\", ":", "/", ".", "<", ">" or new-line
CallStack (from HasCallStack):
  error, called at src/DConf2Nix.hs:35:16 in dconf2nix-0.0.11-FvzjRFPp3Hg72z35IWz5qX:DConf2Nix
```

### DConf input

```ini
[org/gnome/rhythmbox/library]
layout-filename='%tN - %tt'
layout-path='%aa/%at'
```

### Additional context

I can just reset the values and don't see any different behavior in the the application
```
dconf reset /org/gnome/rhythmbox/library/layout-filename
dconf reset /org/gnome/rhythmbox/library/layout-path
```

**Comment by Nebucatnetzer** [comment]
I had this error as well, it happens for a lot of settings which use date formats in their values.
What is the expected solution to this?
